### ISSUE TITLE
Insert of type character varying instead of type enum into Postgres

### ISSUE THREAD

**Issue by dimroth** [prisma/prisma1#2961]
Hi all, thanks for the awesome work !
I am integrating Prisma with an existing Postgres database. When I try to run a basic mutation with an enum value in the playground, I get an internal server error `org.postgresql.util.PSQLException: ERROR: column "gender" is of type "enum_Users_gender" but expression is of type character varying`. I have no problem to make this mutation work using Sequelize and passing a string in parameters.

**To Reproduce**
<details>
  <summary>datamodel.graphql</summary>

```graphql
type User @pgTable(name: "Users") {
  id: UUID! @unique
  firstName: String
  gender: Gender!
}

enum Gender {
  MALE
  FEMALE
}
  ```
</details>

<details>
  <summary>schema.graphql</summary>

```graphql
type User {
  id: UUID!
  firstName: String
  gender: Gender!
}

enum Gender {
  MALE
  FEMALE
}
  ```
</details>

<details>
  <summary>SQL type</summary>

```sql
CREATE TYPE "enum_Users_gender" AS ENUM('MALE', 'FEMALE');
ALTER TABLE "Users" ALTER COLUMN "gender" SET DATA TYPE "enum_Users_gender" USING "gender"::text::"enum_Users_gender";
  ```
</details>

The basic mutation I am trying to execute is :
```graphql
mutation {
  createUser(
    data: {
      firstName: "Dimitri"
      gender: MALE
    }
  ) {
    id
    firstName
  }
}
  ```

**Expected behavior**
Value should be inserted as Enum

**Logs**

```
{"key":"error/unhandled","requestId":"local:api:cjl7qki4c000k0992j294xigo","clientId":"default$default","payload":{"exception":"org.postgresql.util.PSQLException: ERROR: column \"gender\" is of type \"enum_Users_gender\" but expression is of type character varying\n  Hint: You will need to rewrite or cast the expression.\n  Position: 308","query":"mutation {\n  createUser(data: {firstName: \"Dimitri\", gender: MALE}) {\n    id\n    firstName\n  }\n}\n","variables":"{}","code":"0","stack_trace":"org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)\\n org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)\\n org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)\\n org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)\\n org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)\\n org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)\\n org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)\\n com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$insertReturningGeneratedKeysToDBIO$1(BuilderBase.scala:58)\\n com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$jooqToDBIO$1(BuilderBase.scala:81)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"ERROR: column \"gender\" is of type \"enum_Users_gender\" but expression is of type character varying\n  Hint: You will need to rewrite or cast the expression.\n  Position: 308"}}
org.postgresql.util.PSQLException: ERROR: column "gender" is of type "enum_Users_gender" but expression is of type character varying
[Bugsnag - local / testing] Error report: com.bugsnag.Report@620e12e9
  Hint: You will need to rewrite or cast the expression.
  Position: 308
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$insertReturningGeneratedKeysToDBIO$1(BuilderBase.scala:58)
        at com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$jooqToDBIO$1(BuilderBase.scala:81)
        at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
        at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
**Versions :**
 - OS: `OS X High Sierra (build 10.13.6)`
 - `prisma` CLI: `prisma/1.14.2 (darwin-x64) node-v10.6.0`
 - Prisma Server: `1.14`
 - `graphql`: `0.13.2`,
 - `graphql-tag`: `2.9.2`,
 - `graphql-tools`: `3.1.1`,
 - `graphql-yoga`: `1.16.1`,
 - `prisma-binding`: `2.1.4`

**Comment by dimroth** [comment]
FYI, I noticed it works well if I use Postgres Docker image instead of local database.

**Comment by dimroth** [comment]
OK, I get it now, enums are handled as `text` type in the Database and do not use the native Postgres enum type.
