### ISSUE TITLE
Way to change postgresql prisma user password for existing container?

### ISSUE THREAD

**Issue by jiskreq** [prisma/prisma1#3935]
I have docker-compose like in example. I have default user 'prisma' and its password 'prisma'.

Now if i change the password, and run `docker-compose -f docker_compose_config.yml up -d postgres prisma` . After reload i see errors:

```
postgres_1   | 2019-01-25 15:08:07.637 UTC [266] FATAL:  password authentication failed for user "prisma"
postgres_1   | 2019-01-25 15:08:07.637 UTC [266] DETAIL:  Password does not match for user "prisma".
postgres_1   |   Connection matched pg_hba.conf line 95: "host all all all md5"
prisma_1     | Jan 25, 2019 3:08:07 PM org.postgresql.core.v3.ConnectionFactoryImpl log
prisma_1     | WARNING: SQLException occurred while connecting to postgres:5432
prisma_1     | org.postgresql.util.PSQLException: FATAL: password authentication failed for user "prisma"
prisma_1     |   at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
prisma_1     |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
prisma_1     |   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1     |   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1     |   at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1     |   at org.postgresql.Driver.connect(Driver.java:254)
prisma_1     |   at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1     |   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1     |   at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1     |   at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1     |   at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1     |   at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1     |   at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1     |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1     |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1     |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1     |   at java.lang.Thread.run(Thread.java:748)
prisma_1     | 
prisma_1     | Jan 25, 2019 3:08:07 PM org.postgresql.Driver connect
prisma_1     | SEVERE: Connection error: 
prisma_1     | org.postgresql.util.PSQLException: FATAL: password authentication failed for user "prisma"
prisma_1     |   at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
prisma_1     |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
prisma_1     |   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1     |   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1     |   at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1     |   at org.postgresql.Driver.connect(Driver.java:254)
prisma_1     |   at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1     |   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1     |   at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1     |   at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1     |   at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1     |   at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1     |   at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1     |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1     |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1     |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1     |   at java.lang.Thread.run(Thread.java:748)
prisma_1     | 
postgres_1   | 2019-01-25 15:08:07.795 UTC [267] FATAL:  password authentication failed for user "prisma"
postgres_1   | 2019-01-25 15:08:07.795 UTC [267] DETAIL:  Password does not match for user "prisma".
postgres_1   |   Connection matched pg_hba.conf line 95: "host all all all md5"
prisma_1     | Jan 25, 2019 3:08:07 PM org.postgresql.core.v3.ConnectionFactoryImpl log
prisma_1     | WARNING: SQLException occurred while connecting to postgres:5432
prisma_1     | org.postgresql.util.PSQLException: FATAL: password authentication failed for user "prisma"
prisma_1     |   at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
prisma_1     |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionF


```

Maybe i do something wrong?

**Comment by pantharshit00** [comment]
I think either you can completely wipe the volume using

```sh
docker-compose down --rmi all --remove-orphans
```

But this will wipe your data.


You can also try changing it via psql:
```sh
docker exec -it <container-id> psql -U prisma
```

Now you can use this command to change the password:
```sh
\password
```

If this doesn't work use: 

```sql
ALTER USER user_name WITH PASSWORD 'new_password';
```

After changing it also update it in docker-compose
