### ISSUE TITLE
Prisma can't connect to MySQL 8 (Percona)

### ISSUE THREAD

**Issue by mzygmunt** [prisma/prisma1#3979]
**Describe the bug**
When I updated Percona MySQL to version 8.0.13, Prisma 1.25.4 does not connect to the database. This problem also occurs in pure MySQL 8.0.13.

**To Reproduce**
1. Install Prisma 1.25.4
2. Install MySQL 8.0.13
3. See error in Prisma's console

**Expected behavior**
Configuration works fine.

**Screenshots**

**Versions (please complete the following information):**
 - Connector: MySQL
 - DB: MySQL 8.0.13
 - Prisma Server: 1.25.4

**Error**
```
2.02.2019 09:53:28Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5000ms.
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
2.02.2019 09:53:28	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
2.02.2019 09:53:28	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
2.02.2019 09:53:28	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
2.02.2019 09:53:28	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
2.02.2019 09:53:28	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
2.02.2019 09:53:28	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
2.02.2019 09:53:28	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
2.02.2019 09:53:28	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
2.02.2019 09:53:28	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
2.02.2019 09:53:28	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2.02.2019 09:53:28	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2.02.2019 09:53:28	at java.lang.Thread.run(Thread.java:748)
2.02.2019 09:53:28Caused by: java.sql.SQLException: Unsupported transaction isolation level
2.02.2019 09:53:28	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.setTransactionIsolation(AbstractQueryProtocol.java:1261)
2.02.2019 09:53:28	at org.mariadb.jdbc.MariaDbConnection.setTransactionIsolation(MariaDbConnection.java:895)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:378)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
2.02.2019 09:53:28	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
2.02.2019 09:53:28	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2.02.2019 09:53:28	... 3 more
```

**Comment by pantharshit00** [comment]
Prisma currently doesn't support MySQL 8 so we can use this issue as a feature request.

**Comment by JakeHartnell** [comment]
+1

**Comment by iki** [comment]
Is MySQL 8 support planned for Prisma1?

**Comment by darrylyoung** [comment]
> Is MySQL 8 support planned for Prisma1?

Are there any updates on this? I just realised that a Prisma app I built with MySQL won’t deploy to Digital Ocean as they only support MySQL 8.

**Comment by darrylyoung** [comment]
@iki 

> Is MySQL 8 support planned for Prisma1?

As mentioned [here](https://github.com/prisma/prisma2/issues/384#issuecomment-544865374), by somebody in the Prisma team, MySQL 8 will not be supported in Prisma 1.
