### ISSUE TITLE
go/graphql: panicing when sending a lot of requests

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma1#4033]
The GraphQL Go example works fine, but when sending a lot of requests (like 10/second) there is an occasional panic:

```
goroutine 1240 [running]:
runtime/debug.Stack(0x1, 0x0, 0x0)
        /home/luca/.go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /home/luca/.go/src/runtime/debug/stack.go:16 +0x22
github.com/prisma/prisma-examples/go/graphql/vendor/github.com/99designs/gqlgen/graphql.DefaultRecover(0x8eb860, 0xc00045bef0, 0x7fddc0, 0xbb1a50, 0x5e, 0xc0003600f0)
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/vendor/github.com/99designs/gqlgen/graphql/recovery.go:16 +0xa7
main.(*executionContext).FieldMiddleware.func1(0xc000259230, 0x8eb860, 0xc00045bef0, 0xc0003ffe78)
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/server/generated.go:2660 +0x78
panic(0x7fddc0, 0xbb1a50)
        /home/luca/.go/src/runtime/panic.go:513 +0x1b9
main.(*postResolver).Author(0xc000200418, 0x8eb860, 0xc00045bef0, 0xc0002a0420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x203000, ...)
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/server/resolver.go:62 +0x99
main.(*executionContext)._Post_author.func1(0x8eb860, 0xc00045bef0, 0xc0000a8530, 0xc000239e10, 0x20, 0xc000239e08)
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/server/generated.go:895 +0xcc
github.com/prisma/prisma-examples/go/graphql/vendor/github.com/99designs/gqlgen/graphql.DefaultResolverMiddleware(0x8eb860, 0xc00045bef0, 0xc0004b7820, 0x8eb860, 0xc00045bef0, 0xc000239e78, 0xc0004b7820)
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/vendor/github.com/99designs/gqlgen/graphql/context.go:35 +0x3a
main.(*executionContext).FieldMiddleware(0xc000259230, 0x8eb860, 0xc00045bef0, 0x7c0b20, 0xc0002a0420, 0xc0004b7820, 0x0, 0x0)
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/server/generated.go:2664 +0xa1
main.(*executionContext)._Post_author(0xc000259230, 0x8eb860, 0xc0004da750, 0xc000198300, 0xc00045bd70, 0x3, 0x3, 0xc0002a0420, 0xc00024b900, 0x5)
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/server/generated.go:893 +0x1b4
main.(*executionContext)._Post.func1(0xc000259230, 0x8eb860, 0xc0004da750, 0xc0002a0420, 0xc00045be00, 0xc00016b8c8, 0xc00016b8d0, 0x4, 0xc000198300, 0xc00045bd70, ...)
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/server/generated.go:705 +0x81
created by main.(*executionContext)._Post
        /home/luca/go/src/github.com/prisma/prisma-examples/go/graphql/server/generated.go:704 +0x68a
```

This uses a local Prisma+Postgres setup with the latest Go GraphQL Example at https://github.com/prisma/prisma-examples/tree/master/go/graphql

I'm not quite sure what could cause this so feel free to request any additional information you need.

go version go1.11.2
prisma-examples@7f749a882a4d2818304d49907936a70701a6622b
prisma/1.26.4 (linux-x64) node-v10.15.0
prisma server prismagraphql/prisma:1.26

**Comment by pantharshit00** [comment]
I am unable to reproduce this I even tried 20 req/sec. It didn't panic at all.

![image](https://user-images.githubusercontent.com/22195362/52639734-f0e8c880-2efa-11e9-9f05-bc06bcd1aa1d.png)

![image](https://user-images.githubusercontent.com/22195362/52639789-0fe75a80-2efb-11e9-95fb-c32f7bb5679b.png)

**Comment by steebchen** [comment]
Yeah sorry, it turns out it only happens with my specific resolvers.

With the following query, everything works fine even at high load:

```graphql
query {
  feed {
    id
    title
    content

    comments {
      id
      text
    }
  }
}
```

However, if I query the user on comment, an occasional panic happens:

```graphql
query {
  feed {
    id
    title
    content

    comments {
      id
      text
      
      user { # <- this
        id
        name
      }
    }
  }
}
```

The query above works fine, but when sending a lot of requests some requests often panic.

I debugged this and found out that the resolver for `posts.comments.user` sometimes returns a nil pointer, which explains the panic. However, it doesn't explain why sometimes my Prisma query returns a nil pointer.

The relevant line can be found here: https://github.com/steebchen/graphql/issues/2#L31

More info is posted here (for proper inline code):
https://github.com/steebchen/graphql/issues/2

Again, please note that this error occurs **only sometimes**!

I published it so you can hopefully reproduce the issue with the following commands:
```bash
git clone git@github.com:steebchen/graphql.git
cd graphql
docker-compose up -d // starts dev env
prisma deploy // also runs prisma generate & gqlgen
go run ./server
```
