### ISSUE TITLE
Prisma client promise API

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#4179]
**Describe the bug**
Prisma client promise can only be consumed once which is uncommon (maybe even breaks the spec) for promises as even asynchronous promises can be consumed multiple times and once the result it available, it is immediately resolved. 

**To Reproduce**
https://github.com/divyenduz/prisma-4179

**Expected behavior**
Prisma should immediately return the resolved data when a promise is consumed again. Currently, it throws. Here is a stack trace

```
TypeError: Cannot read property 'typeName' of undefined
    at Client.getOperation (/Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/src/Client.ts:103:28)
    at Client.getDocumentForInstructions (/Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/src/Client.ts:113:28)
    at Client.<anonymous> (/Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/src/Client.ts:146:27)
    at step (/Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/dist/Client.js:47:23)
    at Object.next (/Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/dist/Client.js:28:53)
    at /Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/dist/Client.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/dist/Client.js:18:12)
    at Client.processInstructions (/Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/src/Client.ts:140:42)
    at Client.processInstructionsOnce (/Users/divyendusingh/Documents/projects/prisma/triage/support/splunk/node_modules/prisma-client-lib/src/Client.ts:134:33)
```

This happens because the client query builder [overrides `then`, `catch`](https://github.com/prisma/prisma/blob/master/cli/packages/prisma-client-lib/src/Client.ts#L238-L253) and builds the query whenever this promise-like object is consumed and past instruction set (client internal query building meta array) is cleared to avoid memory leaks via https://github.com/prisma/prisma/issues/3732

Prior to the memory-leak fix, this used to work with a network call, each time the promise is consumed. This behavior is also not optimal (same promise should use the network link only once). 

---

**Potential solutions**:

We can build an internal client cache that stores the results of past operations but that would leak memory as we are remembering the results. 

To solve this issue, we can do the following:

1. Either maintain a fixed size queue of remembering past operations to limit the memory usage
2. Provide an API from client to manually clear the memory

**Versions (please complete the following information):**
 - `prisma` CLI: `prisma/1.28.0 (darwin-x64) node-v10.4.0`
 - `prisma-client-lib` CLI: `1.28.0`

**Comment by qirex** [comment]
Also getting this in v1.27.4.

**Comment by qirex** [comment]
Also present in 1.27.1.
Not occuring in 1.24.0.

**Comment by divyenduz** [comment]
Thanks, this will occur in [`1.26.x`](https://github.com/prisma/prisma/issues/3732#issuecomment-465561194) as that is when the memory leak issue was patched and this is a regression.

**Comment by divyenduz** [comment]
This is a demo of how an async promise should behave when consumed multiple times (which is exactly once): https://codesandbox.io/s/q3wj8275lq

The result of that promise is stored as per [this algorithm](https://www.ecma-international.org/ecma-262/6.0/#sec-promise-resolve-functions) in the underlying engine till the promise object is no longer referenced and can be garbage collected. 

Prisma client should match this behavior.

**Comment by smojtabai** [comment]
This is pretty unexpected to me as well, ran into it and spent a long time figuring it out. Any thoughts on fix?
