### ISSUE TITLE
UUID! @id mongo 

### ISSUE THREAD

**Issue by fr4nky80** [prisma/prisma1#5013]
**Describe the bug**
when you use an existing model with UUID it doesn't work properly 

**To Reproduce**
1. Create new project 
2. Use existing database with UUID
3. Go to http://localhost:4466 and launch query
```c#
{
  "data": null,
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:ck6jq94lb000x0781jn3l2orh",
      "path": [
        "otcms"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "requestId": "local:ck6jq94lb000x0781jn3l2orh"
    }
  ]
}
```
**datamodel.prisma**
```c#
type Otcm @db(name: "otcm") {
  id: UUID! @id(strategy: NONE)
  rawType: String
}

```

**Error**
```
Deploying service `default` to stage `default` to server `local` 124ms

Errors:

  Otcm
    × The field `id` is marked as id must have one of the following types: `ID!`.

Deployment canceled. Please fix the above errors to continue deploying.
Read more about deployment errors here: https://bit.ly/prisma-force-flag
```

**Expected behavior**
query with result

**Versions :**
 - Connector: [MongoDB]
 - Prisma Server: [e.g. `1.34.10`]
 - OS: [e.g. `Windows 10`, ]

**Comment by Motonstron** [comment]
Having the same problem with this, when changing to:

`type User @db(name: "users") { 
  _id: ID! @id(strategy: NONE)
  name: String! 
}`

I get the error:

`{ Error: You provided an ID that was not a valid MongoObjectId: dfa3f0cd-3337-4e34-b152-4d6b8aa32b85
    at BatchedGraphQLClient.<anonymous> (/Users/motonstron/Documents/test/node/microservices/prisma/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
    at step (/Users/motonstron/Documents/test/node/microservices/prisma/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/Users/motonstron/Documents/test/node/microservices/prisma/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/Users/motonstron/Documents/test/node/microservices/prisma/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) result: { data: null, errors: [ [Object] ], status: 200 } }`
