### ISSUE TITLE
Could not connect to server at http://localhost:4466

### ISSUE THREAD

**Issue by Khareta** [prisma/prisma1#5033]
**Describe the bug**
$ prisma deploy                                                                                                      
 !   Could not connect to server at http://localhost:4466. Please check if your server is running.
Get in touch if you need help: https://slack.prisma.io
To get more detailed output, run $ export DEBUG="*"

I followed this official prisma tutorial yet it fails: https://www.youtube.com/watch?v=CORQo5rooX8

**To Reproduce**
? Set up a new Prisma server or deploy to an existing server? Use existing database
? What kind of database do you want to deploy to? MySQL
? Does your database contain existing data? Yes
? Enter database host localhost
? Enter database port 3306
? Enter database user root
? Enter database password [hidden]
Introspecting database test 148ms
Created datamodel definition based on 10 tables.
? Select the programming language for the generated Prisma client Prisma JavaScript Client

docker-compose up -d
prisma deploy

**Versions (please complete the following information):**
Connector: MySQL
Prisma CLI version: prisma/1.34.10 (windows-x64) node-v12.16.1
OS: Windows 10

**Additional context**
using docker toolbox
4GB RAM PC

docker logs:

Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Host '172.20.0.2' is not allowed to connect to this MySQL server
        at org.mariadb.jdbc.internal.com.read.ReadInitialHandShakePacket.<init>(ReadInitialHandShakePacket.java:91)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:649)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:402)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)

**Comment by meet8866** [comment]
Same issue....

**Comment by ishan-dawar** [comment]
I'm getting the same error. Did anyone fix it?

**Comment by dhirenchotwani** [comment]
> I'm getting the same error. Did anyone fix it?

Hey Same issue! Did you solve it ?

**Comment by wine379** [comment]
In a nutshell the Prisma team has decided to deprive us the database modeling functionality from Prisma and as such they have decided to give us Prisma 2 wiped out all help links from the internet so that we buy modeling tools. Sad! 

Prisma 1 containers are just restarting and they are silent deliberately.

**Comment by rayedbar** [comment]
Same issue. Sad.
