### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: java.lang.RuntimeException: No valid Prisma config could be loaded.

### ISSUE THREAD

**Issue by EhsanSarshar** [prisma/prisma1#5128]
**Describe the bug**
I just enabled single replica set for mongodb. to be able to track the oplog

**docker-compose.yml**
```
version: "3.4"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      prisma_config: |
        port: 4466
        # uncomment the next line and provide the env var prisma_management_api_secret=my-secret to activate cluster security
        # managementapisecret: my-secret
        databases:
          default:
            connector: mongo
            uri: 'mongodb://user:pass@mongo:27017/?connect=direct'
  mongo:
    # image: mongo:3.6
    image: mongo:4.2.1
    restart: always
    hostname: mongodb
    # ports:
    # - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_REPLICA_SET_NAME: rp0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /Users/initdb.d/:/docker-entrypoint-initdb.d/
      - /Users/mongo-logs/:/var/log/mongodb/
      - mongo:/data/db
      - /Users/mongod.conf:/etc/mongod.conf
      - ~/desktop/mongo-backup/backup-20201019220001:/dump
      # - /opt/mongo-backups:/backups
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ["-f", "/etc/mongod.conf", "--replSet", "$${MONGO_REPLICA_SET_NAME}", "--bind_ip_all"]
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch 
    # hostname: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    # networks:
    #   - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    environment:
      ELASTICSEARCH_URL: http://es01:9200
    ports:
      - 5601:5601 
    # networks:
    #   - elastic

  monstache:
    image: rwynn/monstache:6.7.0
    restart: always
    command: -f /app/monstache.config.toml 
    volumes:
      - $PWD/monstache.config.toml:/app/monstache.config.toml
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    #   es01:
    #     condition: service_healthy
    # networks:
    #   - elastic
    restart: unless-stopped
    healthcheck:
      test: "wget -q -O - http://localhost:8080/healthz"
      interval: 10s
      timeout: 30s
      retries: 300
volumes:
  mongo:
  mongo-conf:
  es01data:

# networks:
#   elastic: 
```

**error trace**
```
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: java.lang.RuntimeException: No valid Prisma config could be loaded.
        at scala.sys.package$.error(package.scala:26)
        at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:40)
        at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:48)
        at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:13)
        at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:8)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:388)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:8)
        at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala
```

**Versions (please complete the following information):**
 - Connector: [`MongoDB`]
 - Prisma Server: [e.g. `1.34`]
 - `prisma` CLI: [e.g. `prisma/1.34.0 (darwin-x64) node-v10.4.0`]
 - OS: [`OS X Mojave`] 
 - other dependencies: `prisma-binding`

**Comment by EhsanSarshar** [comment]
just a case type on .yml file
prisma_config => PRISMA_CONFIG
